// Auto-generated by start-cloudflare-tunneling.bat
// Do not edit manually - tunnelUrl is updated automatically when the tunnel starts
// Set localUrl to your LAN backend address for LAN-first connection
// Last updated: 2026-02-28 20:01:20
window.AUDIOBOOKSHELF_CONFIG = {
  tunnelUrl: 'https://benchmark-viewers-analysis-strip.trycloudflare.com',
  localUrl: 'http://10.0.0.147:8081',
  lastUpdated: '2026-02-28 20:01:20'
};
