#Requires -Version 5.1
<#
    One-line installer for zai-gitter (zai-gitter).

        irm https://phoenixzqy.github.io/install/zai-gitter.ps1 | iex

    Generated by scripts/build-installers.mjs from
    install/templates/installer.ps1.in. Edit the template, not this file, and
    re-run `npm run build:installers`.

    Environment overrides:
      ZAI_INSTALL_DIR           Installation directory (default: %USERPROFILE%\.zai).
      ZAI_RELEASE_MANIFEST_URL  Release manifest URL (used by the test suite).
      ZAI_INSTALL_ARGS          Extra arguments, because `irm | iex` passes none.
#>

Set-StrictMode -Version 1.0
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$appId = 'zai-gitter'
$executable = 'zai-gitter.exe'
$displayName = 'zai-gitter'
$site = 'https://phoenixzqy.github.io'

function Get-ZaiEnv([string] $name) {
    $value = [Environment]::GetEnvironmentVariable($name)
    if ([string]::IsNullOrWhiteSpace($value)) { return $null }
    return $value
}

# Console.Error keeps diagnostics out of the success pipeline, including irm | iex.
function Write-ZaiMessage([string] $level, [string] $message) {
    $colour = ''
    if (-not [Console]::IsErrorRedirected -and $env:TERM -ne 'dumb' -and
        $null -eq [Environment]::GetEnvironmentVariable('NO_COLOR')) {
        switch ($level) {
            'ERROR' { $colour = '1;31' }
            'FAIL' { $colour = '1;31' }
            'WARN' { $colour = '1;33' }
            'NEXT' { $colour = '1;36' }
            'OK' { $colour = '1;32' }
        }
    }
    if ($colour) {
        $escape = [char]27
        [Console]::Error.WriteLine("$escape[${colour}m[$level]$escape[0m $message")
    } else {
        [Console]::Error.WriteLine("[$level] $message")
    }
}
function Stop-Install([string] $message, [int] $code = 1, [string] $next = "Resolve the reason above and rerun the installer. Help: $site/apps/docs/?id=$appId") {
    Write-ZaiMessage 'ERROR' $message
    Write-ZaiMessage 'FAIL' "$displayName installation did not complete."
    Write-ZaiMessage 'NEXT' $next
    exit $code
}

$manifestUrl = Get-ZaiEnv 'ZAI_RELEASE_MANIFEST_URL'
if (-not $manifestUrl) { $manifestUrl = "$site/releases/$appId/latest/manifest.json" }
$installDir = Get-ZaiEnv 'ZAI_INSTALL_DIR'
if (-not $installDir) { $installDir = Join-Path $env:USERPROFILE '.zai' }

# Windows PowerShell 5.1 may still default to TLS 1.0; PowerShell 7 ignores this.
try {
    [Net.ServicePointManager]::SecurityProtocol =
        [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
} catch {
    Write-Verbose 'The TLS 1.2 protocol could not be selected explicitly.'
}

function Get-Architecture {
    try {
        switch ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()) {
            'X64' { return 'x64' }
            'Arm64' { return 'arm64' }
        }
    } catch {
        Write-Verbose 'RuntimeInformation is unavailable; falling back to the environment.'
    }
    $raw = $env:PROCESSOR_ARCHITEW6432
    if ([string]::IsNullOrWhiteSpace($raw)) { $raw = $env:PROCESSOR_ARCHITECTURE }
    switch ($raw) {
        'AMD64' { return 'x64' }
        'ARM64' { return 'arm64' }
    }
    Stop-Install "unsupported processor architecture: $raw. Published builds cover x64 and arm64."
}

function Save-Download([string] $url, [string] $destination) {
    for ($hop = 0; $hop -le 5; $hop++) {
        $uri = $null
        if (-not [Uri]::TryCreate($url, [UriKind]::Absolute, [ref] $uri)) {
            Stop-Install "invalid download URL: $url"
        }
        $localFixture = $hop -eq 0 -and (Get-ZaiEnv 'ZAI_RELEASE_MANIFEST_URL') -and
            $url -cmatch '^http://127\.0\.0\.1(?::[0-9]+)?(?:/|[?#]|$)' -and
            $uri.Host -ceq '127.0.0.1'
        if ($uri.Scheme -ne 'https' -and -not $localFixture) {
            Stop-Install "refusing to download over a non-HTTPS URL: $url"
        }
        # Windows PowerShell 5.1's Invoke-WebRequest can fail before returning
        # a response when MaximumRedirection is zero. Use the .NET transport
        # directly so every redirect is checked before the next request.
        $response = $null
        try {
            $request = [Net.HttpWebRequest]::Create($uri)
            $request.AllowAutoRedirect = $false
            $response = $request.GetResponse()
            $status = [int] $response.StatusCode
            if ($status -ge 300 -and $status -lt 400) {
                if ($localFixture) { Stop-Install "refusing to follow a plaintext redirect: $url" }
                $location = [string] $response.Headers['Location']
                if (-not $location) { Stop-Install "redirect without a Location: $url" }
                $url = [Uri]::new($uri, $location).AbsoluteUri
            } else {
                $stream = $response.GetResponseStream()
                try {
                    $file = [IO.File]::Create($destination)
                    try { $stream.CopyTo($file) } finally { $file.Dispose() }
                } finally { $stream.Dispose() }
                return
            }
        } catch {
            Stop-Install "download failed: $url ($($_.Exception.Message))"
        } finally {
            if ($null -ne $response) { $response.Close() }
        }
    }
    Stop-Install "too many download redirects: $url"
}

function Add-UserPath([string] $directory) {
    # The user PATH is read and written through the registry rather than
    # [Environment]::GetEnvironmentVariable/SetEnvironmentVariable: those expand
    # %VARIABLE% references on read and always write a plain string, which would
    # permanently freeze entries such as %USERPROFILE%\bin to today's value and
    # downgrade REG_EXPAND_SZ to REG_SZ.
    $key = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
    if ($null -eq $key) {
        $key = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey('Environment')
    }
    try {
        $current = $key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
        $kind = if ($null -eq $key.GetValue('Path')) { [Microsoft.Win32.RegistryValueKind]::ExpandString } else { $key.GetValueKind('Path') }
        if ($null -eq $current) { $current = '' }
        $entries = @([string]$current -split ';' | Where-Object { $_ })
        $normalized = $directory.TrimEnd('\')
        foreach ($entry in $entries) {
            if ([Environment]::ExpandEnvironmentVariables($entry).TrimEnd('\') -ieq $normalized) {
                Write-Host "$directory is already on your user PATH."
                return
            }
        }
        $updated = (@($entries) + $directory) -join ';'
        $key.SetValue('Path', $updated, $kind)
        Write-Host "Added $directory to your user PATH."
    } finally {
        $key.Close()
    }
}

function Show-Activation([string] $directory, [string] $command) {
    # irm | iex runs in the calling PowerShell process. The bundled Python
    # installer and registry updates cannot change this process's environment.
    $separator = [IO.Path]::PathSeparator
    $normalized = $directory.TrimEnd([char[]]'\/')
    $present = @($env:PATH -split [regex]::Escape([string]$separator) |
        Where-Object { $_.TrimEnd([char[]]'\/') -ieq $normalized }).Count -gt 0
    if (-not $present) {
        if ([string]::IsNullOrEmpty($env:PATH)) { $env:PATH = $directory }
        else { $env:PATH = $directory + $separator + $env:PATH }
    }

    $quotedDirectory = "'" + $directory.Replace("'", "''") + "'"
    Write-Host ''
    Write-Host '[NEXT] Ready in this PowerShell session. Run:'
    $quotedCommand = "'" + $command.Replace("'", "''") + "'"
    Write-Host ("  & " + $quotedCommand)
    Write-Host ''
    Write-Host 'If the installer ran in a separate process, activate your calling PowerShell terminal:'
    Write-Host ('  $env:Path = ' + $quotedDirectory + ' + [IO.Path]::PathSeparator + $env:Path')
    Write-Host ("  & " + $quotedCommand)
}
function Install-Shortcut([string] $directory, [string] $name, [string] $command) {
    if (-not (Test-Path -LiteralPath (Join-Path $directory "$command.exe") -PathType Leaf)) { return }
    $launcher = Join-Path $directory "$name.cmd"
    $taken = (Get-Command $name -All -ErrorAction SilentlyContinue) -or
        (Get-Item -LiteralPath $launcher -Force -ErrorAction SilentlyContinue)
    # CMD also searches its current directory, unlike PowerShell.
    $currentDirectories = @($directory, [Environment]::CurrentDirectory)
    $location = Get-Location
    if ($location.Provider.Name -eq 'FileSystem') { $currentDirectories += $location.ProviderPath }
    $extensions = @('') + @($env:PATHEXT -split ';') + @('.exe', '.cmd', '.bat', '.com', '.ps1')
    foreach ($currentDirectory in $currentDirectories) {
        foreach ($extension in $extensions) {
            if (Get-Item -LiteralPath (Join-Path $currentDirectory ($name + $extension)) -Force -ErrorAction SilentlyContinue) {
                $taken = $true
            }
        }
    }
    # A PowerShell child of CMD shares the console's DOSKEY macros.
    if ($env:OS -eq 'Windows_NT') {
        $doskey = Join-Path $env:SystemRoot 'System32\doskey.exe'
        if (Test-Path -LiteralPath $doskey) {
            if (& $doskey /macros:cmd.exe | Where-Object { $_ -imatch ('^' + [regex]::Escape($name) + '=') }) {
                $taken = $true
            }
        }
    }
    if ($taken) {
        Write-Host "Skipped shortcut ${name}: the name is already taken."
        return
    }
    # A relative CMD launcher works in both PowerShell and CMD, forwards all
    # arguments, and always follows updates to the canonical executable.
    $content = "@echo off`r`nrem zai shortcut: $name -> $command`r`n`"%~dp0$command.exe`" %*`r`n"
    $bytes = [Text.Encoding]::ASCII.GetBytes($content)
    try {
        $stream = [IO.File]::Open($launcher, [IO.FileMode]::CreateNew, [IO.FileAccess]::Write, [IO.FileShare]::None)
    } catch [IO.IOException] {
        Write-Host "Skipped shortcut ${name}: the launcher could not be created."
        return
    }
    try { $stream.Write($bytes, 0, $bytes.Length) } finally { $stream.Dispose() }
    Write-Host "Installed shortcut: $name -> $command"
}
$architecture = Get-Architecture
$work = Join-Path ([System.IO.Path]::GetTempPath()) ("zai-install-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $work -Force | Out-Null

try {
    $manifestFile = Join-Path $work 'manifest.json'
    Save-Download $manifestUrl $manifestFile
    try {
        $manifest = Get-Content -Path $manifestFile -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
        Stop-Install "the release manifest at $manifestUrl could not be read as JSON."
    }

    if ($null -eq $manifest.release) {
        Stop-Install "No public release of $displayName has been published yet." 2 "Watch $site/apps/app/?id=$appId for the first build."
    }

    $assets = @($manifest.release.assets |
        Where-Object {
            $_.platform -eq 'windows' -and
            $_.architecture -eq $architecture -and
            ([string] $_.file) -match '\.zip$'
        })
    if ($assets.Count -eq 0) {
        Stop-Install "the published release has no package for windows/$architecture. See $site/apps/releases/?id=$appId for the packages that are available."
    }
    if ($assets.Count -gt 1) {
        Stop-Install "the release manifest contains multiple ZIP packages for windows/$architecture. Refusing to choose one ambiguously."
    }
    $asset = $assets[0]
    if ($asset.file -match '[\\/]' -or $asset.file -match '\.\.') {
        Stop-Install "the manifest package name is not a plain filename: $($asset.file)"
    }

    $assetUrl = Get-Member -InputObject $asset -Name 'url' -MemberType NoteProperty |
        ForEach-Object { $asset.url }
    if ([string]::IsNullOrWhiteSpace($assetUrl)) {
        $assetUrl = ($manifestUrl -replace '/[^/]*$', '') + '/' + $asset.file
    }

    $archive = Join-Path $work $asset.file
    Write-Host "[INFO] Downloading $displayName for windows/$architecture..."
    Save-Download $assetUrl $archive

    $actualHash = (Get-FileHash -Path $archive -Algorithm SHA256).Hash.ToLowerInvariant()
    $expectedHash = ([string] $asset.sha256).ToLowerInvariant()
    if ($actualHash -ne $expectedHash) {
        Stop-Install "SHA-256 verification failed for $($asset.file).`n  expected: $expectedHash`n  actual:   $actualHash`nThe download was discarded and nothing was installed."
    }
    $actualBytes = (Get-Item -Path $archive).Length
    $expectedBytes = Get-Member -InputObject $asset -Name 'bytes' -MemberType NoteProperty |
        ForEach-Object { $asset.bytes }
    if ($expectedBytes -and $actualBytes -ne $expectedBytes) {
        Stop-Install "the downloaded package is $actualBytes bytes but the manifest declares $expectedBytes. Nothing was installed."
    }
    Write-Host "[OK] Verified SHA-256 $expectedHash"

    $extract = Join-Path $work 'extract'
    New-Item -ItemType Directory -Path $extract -Force | Out-Null
    try {
        Expand-Archive -Path $archive -DestinationPath $extract -Force
    } catch {
        Stop-Install "the downloaded archive could not be extracted: $($_.Exception.Message)"
    }

    # --- Install ----------------------------------------------------------
    $binary = Get-ChildItem -Path $extract -Filter $executable -Recurse -File |
        Select-Object -First 1
    if ($null -eq $binary) {
        Stop-Install "the package did not contain an executable named '$executable'. Nothing was installed."
    }

    New-Item -ItemType Directory -Path $installDir -Force | Out-Null
    $target = Join-Path $installDir $executable
    Copy-Item -Path $binary.FullName -Destination $target -Force

    $licenseDir = Join-Path (Join-Path $installDir 'licenses') $appId
    if (Test-Path $licenseDir) { Remove-Item -Path $licenseDir -Recurse -Force }
    New-Item -ItemType Directory -Path $licenseDir -Force | Out-Null
    Get-ChildItem -Path $extract -Recurse -File |
        Where-Object { $_.Name -match '^(LICENSE|NOTICE|COPYING|THIRD[-_]PARTY)' } |
        ForEach-Object { Copy-Item -Path $_.FullName -Destination $licenseDir -Force }

    Add-UserPath $installDir
    Install-Shortcut $installDir 'zg' 'zai-gitter'

    Write-ZaiMessage 'OK' "$displayName installation complete."
    Write-Host ''
    Write-Host 'Installed command: zai-gitter'
    Write-Host "Installed $displayName to $target"
    Write-Host "Licenses: $licenseDir"
    Show-Activation $installDir 'zai-gitter'
    Write-Host "Documentation: $site/apps/docs/?id=$appId"
} catch {
    Stop-Install $_.Exception.Message
} finally {
    Remove-Item -Path $work -Recurse -Force -ErrorAction SilentlyContinue
}
