#Requires -Version 5.1
# Generated by scripts/build-installers.mjs; edit the templates, not this file.
# Reviewed public installer: phoenixzqy/zai-codex, branch zai-codex, commit 1cca747cf793d9ea3c382c487761d24ebdc834f8.
# Python 3.10+ required. ZAI_INSTALL_DIR and ZAI_RELEASE_MANIFEST_URL are supported.
# irm https://phoenixzqy.github.io/install/zai-codex.ps1 | iex
$ErrorActionPreference = 'Stop'
# Console.Error keeps diagnostics out of the success pipeline, including irm | iex.
function Write-ZaiMessage([string] $level, [string] $message) {
    $colour = ''
    if (-not [Console]::IsErrorRedirected -and $env:TERM -ne 'dumb' -and
        $null -eq [Environment]::GetEnvironmentVariable('NO_COLOR')) {
        switch ($level) {
            'ERROR' { $colour = '1;31' }
            'FAIL' { $colour = '1;31' }
            'WARN' { $colour = '1;33' }
            'NEXT' { $colour = '1;36' }
            'OK' { $colour = '1;32' }
        }
    }
    if ($colour) {
        $escape = [char]27
        [Console]::Error.WriteLine("$escape[${colour}m[$level]$escape[0m $message")
    } else {
        [Console]::Error.WriteLine("[$level] $message")
    }
}
function Show-Activation([string] $directory, [string] $command) {
    # irm | iex runs in the calling PowerShell process. The bundled Python
    # installer and registry updates cannot change this process's environment.
    $separator = [IO.Path]::PathSeparator
    $normalized = $directory.TrimEnd([char[]]'\/')
    $present = @($env:PATH -split [regex]::Escape([string]$separator) |
        Where-Object { $_.TrimEnd([char[]]'\/') -ieq $normalized }).Count -gt 0
    if (-not $present) {
        if ([string]::IsNullOrEmpty($env:PATH)) { $env:PATH = $directory }
        else { $env:PATH = $directory + $separator + $env:PATH }
    }

    $quotedDirectory = "'" + $directory.Replace("'", "''") + "'"
    Write-Host ''
    Write-Host '[NEXT] Ready in this PowerShell session. Run:'
    $quotedCommand = "'" + $command.Replace("'", "''") + "'"
    Write-Host ("  & " + $quotedCommand)
    Write-Host ''
    Write-Host 'If the installer ran in a separate process, activate your calling PowerShell terminal:'
    Write-Host ('  $env:Path = ' + $quotedDirectory + ' + [IO.Path]::PathSeparator + $env:Path')
    Write-Host ("  & " + $quotedCommand)
}
$python = Get-Command python -ErrorAction SilentlyContinue
if (-not $python) { Write-ZaiMessage 'ERROR' 'Python 3.10+ is required.'; Write-ZaiMessage 'FAIL' 'zai-codex installation did not start.'; Write-ZaiMessage 'NEXT' 'Install Python from https://www.python.org/downloads/, open a new terminal, and rerun the installer.'; exit 1 }
$installer = @'
#!/usr/bin/env python3
"""Download a verified custom release and install the codex command."""

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import platform
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import zipfile


REPOSITORY = "phoenixzqy/zai-codex"
SITE = "https://phoenixzqy.github.io"
TAG_PATTERN = re.compile(r"zai-codex-v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?")
WINDOWS_MARKER = "@rem zai-codex release launcher\n"


def host_target():
    system = platform.system()
    machine = platform.machine().lower()
    arch = {"amd64": "x86_64", "arm64": "aarch64"}.get(machine, machine)
    suffix = {
        "Linux": "unknown-linux-gnu",
        "Darwin": "apple-darwin",
        "Windows": "pc-windows-msvc",
    }.get(system)
    if arch not in ("x86_64", "aarch64") or suffix is None:
        raise ValueError(f"Unsupported platform: {system} {machine}")
    return f"{arch}-{suffix}"


def download(url, destination):
    def check_url(value):
        parsed = urllib.parse.urlsplit(value)
        if parsed.scheme == "https" and not parsed.username and not parsed.password:
            return
        if (
            os.environ.get("ZAI_RELEASE_MANIFEST_URL")
            and parsed.scheme == "http"
            and parsed.hostname == "127.0.0.1"
        ):
            return
        raise ValueError("Downloads require HTTPS")

    class RedirectHandler(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, request, response, code, message, headers, newurl):
            check_url(newurl)
            if urllib.parse.urlsplit(newurl).scheme != "https":
                raise ValueError("HTTPS redirects must stay on HTTPS")
            if urllib.parse.urlsplit(request.full_url).scheme != "https":
                raise ValueError("Local test downloads must not redirect")
            return super().redirect_request(
                request, response, code, message, headers, newurl
            )

    check_url(url)
    request = urllib.request.Request(url, headers={"User-Agent": "zai-codex-installer"})
    with urllib.request.build_opener(RedirectHandler()).open(
        request, timeout=120
    ) as response:
        with destination.open("wb") as output:
            shutil.copyfileobj(response, output)


def verified_extract(archive_path, checksum, destination):
    expected = checksum.strip()
    if not re.fullmatch(r"[0-9a-f]{64}", expected):
        raise ValueError("Invalid release SHA-256")
    digest = hashlib.sha256()
    with archive_path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    if digest.hexdigest() != expected:
        raise ValueError("Release SHA-256 mismatch")

    def output_path(name):
        path = PurePosixPath(name)
        if path.is_absolute() or ".." in path.parts or "\\" in name or ":" in name:
            raise ValueError(f"Unsafe archive path: {name}")
        result = destination.joinpath(*path.parts)
        if not result.resolve().is_relative_to(destination.resolve()):
            raise ValueError(f"Unsafe archive path: {name}")
        return result

    def copy_member(name, mode, source):
        path = output_path(name)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("xb") as output:
            shutil.copyfileobj(source, output)
        path.chmod(0o755 if mode & 0o111 else 0o644)

    with zipfile.ZipFile(archive_path) as archive:
        for member in archive.infolist():
            mode = member.external_attr >> 16
            if stat.S_IFMT(mode) not in (0, stat.S_IFREG, stat.S_IFDIR):
                raise ValueError("Archive links and special files are not allowed")
            if member.is_dir():
                output_path(member.filename).mkdir(parents=True, exist_ok=True)
            else:
                with archive.open(member) as source:
                    copy_member(member.filename, mode, source)


def validate_package(package, target, tag):
    metadata = json.loads((package / "codex-package.json").read_text())
    provenance = json.loads((package / "zai-release.json").read_text())
    windows = target.endswith("windows-msvc")
    suffix = ".exe" if windows else ""
    if any(
        metadata.get(key) != value
        for key, value in {
            "layoutVersion": 1,
            "target": target,
            "variant": "codex",
            "entrypoint": f"bin/codex{suffix}",
        }.items()
    ):
        raise ValueError("Release package metadata mismatch")
    if (
        provenance.get("repository") != REPOSITORY
        or provenance.get("branch") != "zai-codex"
        or provenance.get("tag") != tag
        or provenance.get("version") != tag.removeprefix("zai-codex-v")
        or not re.fullmatch(r"[0-9a-f]{40}", provenance.get("commit", ""))
    ):
        raise ValueError("Custom release provenance mismatch")
    required = [
        f"bin/codex{suffix}",
        f"bin/codex-code-mode-host{suffix}",
        f"codex-path/rg{suffix}",
        "LICENSE",
        "NOTICE",
        "MODIFICATIONS.txt",
    ]
    if "linux" in target:
        required.append("codex-resources/bwrap")
    if windows:
        required.extend(
            [
                "codex-resources/codex-command-runner.exe",
                "codex-resources/codex-windows-sandbox-setup.exe",
            ]
        )
    if not all((package / name).is_file() for name in required):
        raise ValueError("Incomplete custom release package")
    if not (package / "third-party-notices").is_dir():
        raise ValueError("Missing third-party notices")
    binary = package / f"bin/codex{suffix}"
    result = subprocess.run(
        [str(binary), "--version"], check=True, capture_output=True, text=True
    )
    if result.stdout.strip() != f"codex-cli {metadata.get('version')}":
        raise ValueError("Package version does not match its executable")
    subprocess.run(
        [str(binary), "login", "github-copilot", "--help"],
        check=True,
        stdout=subprocess.DEVNULL,
    )


def launcher_state(launcher, root, windows):
    if launcher.is_symlink():
        if windows or not launcher.resolve().is_relative_to(root):
            raise ValueError(f"Refusing to replace a foreign launcher: {launcher}")
        return str(launcher.readlink())
    if launcher.exists():
        if windows and launcher.is_file():
            text = launcher.read_text()
            if text.startswith(WINDOWS_MARKER):
                return text
        raise ValueError(f"Refusing to replace an existing executable: {launcher}")
    return None


def install(archive, checksum, tag, target, root, launcher):
    root = root.expanduser().resolve()
    launcher = launcher.expanduser()
    launcher.parent.mkdir(parents=True, exist_ok=True)
    launcher = launcher.parent.resolve() / launcher.name
    windows = target.endswith("windows-msvc")
    previous = launcher_state(launcher, root, windows)
    root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".zai-stage-", dir=root) as temporary:
        package = Path(temporary) / "package"
        package.mkdir()
        verified_extract(archive, checksum, package)
        validate_package(package, target, tag)
        if launcher_state(launcher, root, windows) != previous:
            raise ValueError("Install destination changed during download")
        destination = root / f"{tag}-{target}-{Path(temporary).name}"
        package.rename(destination)
        try:
            with tempfile.TemporaryDirectory(
                prefix=".zai-launcher-", dir=launcher.parent
            ) as staging:
                staged = Path(staging) / launcher.name
                if windows:
                    binary = str(destination / "bin/codex.exe")
                    if any(char in binary for char in '%"\r\n'):
                        raise ValueError("Unsupported Windows install path")
                    staged.write_text(
                        WINDOWS_MARKER
                        + "@setlocal DisableDelayedExpansion\n"
                        + f'@"{binary}" %*\n'
                    )
                else:
                    staged.symlink_to(destination / "bin/codex")
                staged.replace(launcher)
        except BaseException:
            shutil.rmtree(destination)
            raise
    print(f"Installed {tag}: {launcher}")
    print(f"Add {launcher.parent} to PATH if needed, then run codex.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    if sys.version_info < (3, 10):
        raise ValueError("Python 3.10+ is required")
    manifest_url = os.environ.get(
        "ZAI_RELEASE_MANIFEST_URL", f"{SITE}/releases/zai-codex/latest/manifest.json"
    )
    with tempfile.TemporaryDirectory(prefix="zai-codex-download-") as temporary:
        temporary = Path(temporary)
        metadata = temporary / "manifest.json"
        download(manifest_url, metadata)
        manifest = json.loads(metadata.read_text())
        if manifest.get("schemaVersion") != 1 or manifest.get("appId") != "zai-codex":
            raise ValueError("Custom release manifest mismatch")
        release = manifest["release"]
        if release is None:
            raise ValueError("No public release of zai-codex has been published yet")
        tag = f"zai-codex-v{release['version']}"
        if not TAG_PATTERN.fullmatch(tag):
            raise ValueError(f"Not a custom zai-codex release: {tag}")
        target = host_target()
        platform_id = {"Linux": "linux", "Darwin": "macos", "Windows": "windows"}[
            platform.system()
        ]
        architecture = "arm64" if target.startswith("aarch64") else "x64"
        matches = [
            asset
            for asset in release["assets"]
            if asset.get("platform") == platform_id
            and asset.get("architecture") == architecture
        ]
        if len(matches) != 1:
            raise ValueError(
                f"No unique published package for {platform_id}/{architecture}"
            )
        asset = matches[0]
        name = f"zai-codex-{release['version']}-{target}.zip"
        if asset["file"] != name:
            raise ValueError("Custom package filename mismatch")
        url = asset.get("url", urllib.parse.urljoin(manifest_url, name))
        allowed = {
            f"https://github.com/phoenixzqy/{repository}/releases/download/{tag}/{name}"
            for repository in ("phoenixzqy.github.io", "zai-codex")
        }
        local = urllib.parse.urljoin(manifest_url, name)
        if url not in allowed and url != local:
            raise ValueError(
                "Package URL must use an approved custom release or manifest folder"
            )
        archive = temporary / name
        download(url, archive)
        if (
            type(asset["bytes"]) is not int
            or asset["bytes"] <= 0
            or archive.stat().st_size != asset["bytes"]
        ):
            raise ValueError("Release byte count mismatch")
        install_dir = os.environ.get("ZAI_INSTALL_DIR")
        root = Path(
            os.environ.get(
                "ZAI_CODEX_INSTALL_ROOT",
                str(Path(install_dir) / "releases/zai-codex")
                if install_dir
                else "~/.local/lib/zai-codex",
            )
        )
        launcher = Path(
            os.environ.get(
                "ZAI_CODEX_BIN_LINK",
                str(
                    Path(install_dir or "~/.local/bin")
                    / ("codex.cmd" if target.endswith("windows-msvc") else "codex")
                ),
            )
        )
        install(archive, asset["sha256"], tag, target, root, launcher)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except urllib.error.HTTPError as error:
        raise SystemExit(
            f"Custom release download failed ({error.code}); no upstream fallback."
        )
    except (
        OSError,
        ValueError,
        KeyError,
        TypeError,
        AttributeError,
        zipfile.BadZipFile,
        subprocess.SubprocessError,
    ) as error:
        raise SystemExit(str(error))
'@
$runner = @'
# Keep stdout and stdin live for interactive installers. Do not buffer output,
# parse English messages, or guess whether a diagnostic is an error or warning.
import sys
import runpy
import traceback

# Shared presentation only: installation/removal decisions belong to the app.
def zai_message(level, text):
    import os
    import sys

    colours = {"ERROR": "1;31", "FAIL": "1;31", "WARN": "1;33", "NEXT": "1;36", "OK": "1;32"}
    label = f"[{level}]"
    if sys.stderr.isatty() and os.environ.get("TERM") != "dumb" and "NO_COLOR" not in os.environ:
        colour = colours.get(level)
        if colour:
            label = f"\033[{colour}m{label}\033[0m"
    print(f"{label} {text}", file=sys.stderr, flush=True)

class ZaiDiagnostics:
    def __init__(self, stream):
        self.stream = stream
        self.at_start = True

    def write(self, text):
        for part in text.splitlines(keepends=True):
            if self.at_start and part.strip():
                self.stream.write("[DETAIL] ")
            self.stream.write(part)
            self.at_start = part.endswith("\n")
        self.stream.flush()
        return len(text)

    def flush(self):
        self.stream.flush()

    def __getattr__(self, name):
        return getattr(self.stream, name)

label, mode = sys.argv[1:3]
sys.argv = sys.argv[3:]
original_stderr = sys.stderr
sys.stderr = ZaiDiagnostics(original_stderr)
code = 0
reason = None
try:
    if mode == "stdin":
        # The reviewed source remains unchanged in its original here-document.
        sys.argv.insert(0, "-")
        exec(compile(sys.stdin.read(), "<stdin>", "exec"), {"__name__": "__main__", "__file__": "<stdin>"})
    else:
        sys.path.insert(0, str(__import__("pathlib").Path(sys.argv[0]).resolve().parent))
        runpy.run_path(sys.argv[0], run_name="__main__")
except SystemExit as error:
    if error.code is None:
        code = 0
    elif isinstance(error.code, int):
        code = error.code
    else:
        reason, code = str(error.code), 1
except KeyboardInterrupt:
    reason, code = "Installation interrupted.", 130
except Exception as error:
    traceback.print_exc()
    reason, code = str(error), 1
finally:
    sys.stderr = original_stderr

if code:
    if reason:
        zai_message("ERROR", reason)
    zai_message("FAIL", f"{label}: the bundled package installer did not complete (exit {code}).")
    zai_message("NEXT", "Resolve the reason shown above, then rerun the install/update command. If an app is running, close it completely first; for zai, attach with zai and choose Close completely.")
raise SystemExit(code)
'@
$runnerPath = [IO.Path]::GetTempFileName()
try {
    [IO.File]::WriteAllText($runnerPath, $runner, (New-Object Text.UTF8Encoding($false)))
    # Native stderr is diagnostic output; the exit code determines failure.
    $ErrorActionPreference = 'Continue'
    $installer | & $python.Source -B $runnerPath 'zai-codex installer' stdin
    $installerExitCode = $LASTEXITCODE
} finally {
    $ErrorActionPreference = 'Stop'
    Remove-Item -LiteralPath $runnerPath -Force
}
if ($installerExitCode -ne 0) { exit $installerExitCode }
Write-ZaiMessage 'OK' 'zai-codex installation complete.'
$resolveLauncher = @'
import os
from pathlib import Path
launcher = Path(os.environ.get("ZAI_CODEX_BIN_LINK", str(Path(os.environ.get("ZAI_INSTALL_DIR") or "~/.local/bin") / "codex.cmd"))).expanduser()
print(launcher.parent.resolve())
print(launcher.name)
'@
$launcherLocation = $resolveLauncher | & $python.Source -B -
if ($LASTEXITCODE -ne 0) { Write-ZaiMessage 'ERROR' 'Could not resolve the installed launcher directory.'; Write-ZaiMessage 'NEXT' 'Check ZAI_CODEX_BIN_LINK and ZAI_INSTALL_DIR, then rerun the installer.'; exit $LASTEXITCODE }
Show-Activation $launcherLocation[0] $launcherLocation[1]
