#!/bin/sh
# One-line installer for zai (zai-cli).
#
#   curl -fsSL https://phoenixzqy.github.io/install/zai-cli.sh | sh
#
# Generated by scripts/build-installers.mjs from
# install/templates/installer.sh.in. Edit the template, not this file, and
# re-run `npm run build:installers`.
#
# Environment overrides:
#   ZAI_INSTALL_DIR            Installation directory (default: $HOME/.zai).
#   ZAI_RELEASE_MANIFEST_URL   Release manifest URL (used by the test suite).
set -eu

APP_ID='zai-cli'
EXECUTABLE='zai'
DISPLAY_NAME='zai'
SITE='https://phoenixzqy.github.io'
MANIFEST_URL="${ZAI_RELEASE_MANIFEST_URL:-$SITE/releases/$APP_ID/latest/manifest.json}"
INSTALL_DIR="${ZAI_INSTALL_DIR:-$HOME/.zai}"

WORK=''
cleanup() {
  if [ -n "$WORK" ]; then
    rm -rf "$WORK"
  fi
}
trap cleanup EXIT HUP INT TERM

fail() {
  printf '%s installer: %s\n' "$DISPLAY_NAME" "$1" >&2
  exit 1
}
info() {
  printf '%s\n' "$1"
}

# --- Platform -------------------------------------------------------------
case "$(uname -s)" in
  Linux*) PLATFORM=linux ;;
  Darwin*) PLATFORM=macos ;;
  *) fail "unsupported operating system: $(uname -s). Published builds cover Linux (including WSL) and macOS here; on Windows run the PowerShell installer at $SITE/install/$APP_ID.ps1." ;;
esac
case "$(uname -m)" in
  x86_64 | amd64) ARCHITECTURE=x64 ;;
  aarch64 | arm64) ARCHITECTURE=arm64 ;;
  *) fail "unsupported processor architecture: $(uname -m). Published builds cover x86_64/amd64 and aarch64/arm64." ;;
esac

# --- Tools ----------------------------------------------------------------
if command -v curl >/dev/null 2>&1; then
  DOWNLOADER=curl
elif command -v wget >/dev/null 2>&1; then
  DOWNLOADER=wget
else
  fail 'neither curl nor wget was found. Install one of them and run the command again.'
fi

require_https() {
  case "$1" in
    https://*) return 0 ;;
  esac
  if [ -n "${ZAI_RELEASE_MANIFEST_URL:-}" ]; then
    return 0
  fi
  fail "refusing to download over a non-HTTPS URL: $1"
}

download() {
  require_https "$1"
  case "$DOWNLOADER" in
    curl) curl -fsSL -o "$2" "$1" || fail "download failed: $1" ;;
    wget) wget -q -O "$2" "$1" || fail "download failed: $1" ;;
  esac
}

checksum() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    fail 'no SHA-256 tool was found. Install sha256sum (coreutils) or shasum and run the command again.'
  fi
}

extract() {
  if command -v unzip >/dev/null 2>&1; then
    unzip -q "$1" -d "$2" || fail 'the downloaded archive could not be extracted with unzip.'
  elif command -v bsdtar >/dev/null 2>&1; then
    bsdtar -xf "$1" -C "$2" || fail 'the downloaded archive could not be extracted with bsdtar.'
  elif tar -xf "$1" -C "$2" 2>/dev/null; then
    :
  elif command -v python3 >/dev/null 2>&1; then
    python3 -m zipfile -e "$1" "$2" || fail 'the downloaded archive could not be extracted with python3.'
  else
    fail 'no ZIP extraction tool was found. Install unzip, bsdtar, or python3 and run the command again.'
  fi
}

ensure_on_path() {
  marker='# Added by zai installer'
  line="export PATH=\"$1:\$PATH\"  $marker"
  profiles="$HOME/.profile"
  case "${SHELL:-}" in
    *zsh*) profiles="$profiles $HOME/.zshrc" ;;
    *bash*) profiles="$profiles $HOME/.bashrc" ;;
    *) profiles="$profiles $HOME/.bashrc $HOME/.zshrc" ;;
  esac
  for profile in $profiles; do
    # Match the exact line, not the marker: an earlier install into a
    # different directory must not make this one think PATH is already set.
    if [ -f "$profile" ] && grep -Fqx "$line" "$profile"; then
      continue
    fi
    if [ -f "$profile" ] && [ -n "$(tail -c 1 "$profile" 2>/dev/null)" ]; then
      printf '\n' >>"$profile" || continue
    fi
    printf '%s\n' "$line" >>"$profile" 2>/dev/null || continue
    info "Added $1 to PATH in $profile"
  done
}

# --- Manifest -------------------------------------------------------------
WORK="$(mktemp -d 2>/dev/null || mktemp -d -t zai-install)" ||
  fail 'a temporary directory could not be created.'
MANIFEST="$WORK/manifest.json"
download "$MANIFEST_URL" "$MANIFEST"

if grep -Eq '"release"[[:space:]]*:[[:space:]]*null' "$MANIFEST"; then
  printf '%s\n' "No public release of $DISPLAY_NAME has been published yet." >&2
  printf '%s\n' "Watch $SITE/apps/app/?id=$APP_ID for the first build." >&2
  exit 2
fi

# The publishing contract stores one manifest field per line, so a line-based
# reader keeps this script free of any JSON dependency.
ASSET="$(awk -v want_platform="$PLATFORM" -v want_arch="$ARCHITECTURE" '
  function value(line) {
    sub(/^[^:]*:[ \t]*/, "", line)
    sub(/,[ \t]*$/, "", line)
    gsub(/^"|"$/, "", line)
    return line
  }
  function reset() { platform = ""; arch = ""; file = ""; url = ""; sha = ""; bytes = "" }
  BEGIN { reset(); found = 0 }
  found { next }
  /^[ \t]*\{[ \t]*$/ { reset(); next }
  /^[ \t]*"platform"[ \t]*:/ { platform = value($0); next }
  /^[ \t]*"architecture"[ \t]*:/ { arch = value($0); next }
  /^[ \t]*"file"[ \t]*:/ { file = value($0); next }
  /^[ \t]*"url"[ \t]*:/ { url = value($0); next }
  /^[ \t]*"sha256"[ \t]*:/ { sha = value($0); next }
  /^[ \t]*"bytes"[ \t]*:/ { bytes = value($0); next }
  /^[ \t]*\}[ \t]*,?[ \t]*$/ {
    if (platform == want_platform && arch == want_arch && file != "" && sha != "") {
      print file; print url; print sha; print bytes
      found = 1
    }
    reset()
  }
' "$MANIFEST")"

[ -n "$ASSET" ] ||
  fail "the published release has no package for $PLATFORM/$ARCHITECTURE. See $SITE/apps/releases/?id=$APP_ID for the packages that are available."

ASSET_FILE="$(printf '%s\n' "$ASSET" | sed -n 1p)"
ASSET_URL="$(printf '%s\n' "$ASSET" | sed -n 2p)"
ASSET_SHA="$(printf '%s\n' "$ASSET" | sed -n 3p)"
ASSET_BYTES="$(printf '%s\n' "$ASSET" | sed -n 4p)"

case "$ASSET_FILE" in
  */* | *..* | '') fail "the manifest package name is not a plain filename: $ASSET_FILE" ;;
esac
if [ -z "$ASSET_URL" ]; then
  ASSET_URL="${MANIFEST_URL%/*}/$ASSET_FILE"
fi

# --- Download and verify --------------------------------------------------
ARCHIVE="$WORK/$ASSET_FILE"
info "Downloading $DISPLAY_NAME for $PLATFORM/$ARCHITECTURE…"
download "$ASSET_URL" "$ARCHIVE"

ACTUAL_SHA="$(checksum "$ARCHIVE")"
if [ "$ACTUAL_SHA" != "$ASSET_SHA" ]; then
  fail "SHA-256 verification failed for $ASSET_FILE.
  expected: $ASSET_SHA
  actual:   $ACTUAL_SHA
The download was discarded and nothing was installed."
fi
if [ -n "$ASSET_BYTES" ]; then
  ACTUAL_BYTES="$(wc -c <"$ARCHIVE" | tr -d ' ')"
  if [ "$ACTUAL_BYTES" != "$ASSET_BYTES" ]; then
    fail "the downloaded package is $ACTUAL_BYTES bytes but the manifest declares $ASSET_BYTES. Nothing was installed."
  fi
fi
info "Verified SHA-256 $ASSET_SHA"

EXTRACT="$WORK/extract"
mkdir -p "$EXTRACT"
extract "$ARCHIVE" "$EXTRACT"

# --- Install --------------------------------------------------------------
# zai ships a Python package installer at the root of the archive. It performs
# the real installation (executable, agent homes, PATH) and reports its own
# result. The entry point is exactly 'install.py' beside its '_installer.py'
# library; the archive carries other .py files that must never be run instead.
PYTHON=''
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1; then
    PYTHON="$candidate"
    break
  fi
done
[ -n "$PYTHON" ] ||
  fail "Python 3.10 or newer is required but no 'python3' was found on PATH. Install Python, then run the command again."

PACKAGE_INSTALLER="$EXTRACT/install.py"
[ -f "$PACKAGE_INSTALLER" ] ||
  fail "the package did not contain 'install.py' at its root. Nothing was installed."

if [ -n "${ZAI_INSTALL_DIR:-}" ]; then
  set -- --install-dir "$INSTALL_DIR" "$@"
fi

info "Running the bundled package installer with $PYTHON…"
# The script itself arrives on stdin when piped to sh, so reattach the terminal
# where one is actually usable; the package installer may ask before installing
# the agent CLI. Probe in a subshell: /dev/tty can exist and still not open,
# and a redirection error on a compound command would end this script.
if (exec 3</dev/tty) 2>/dev/null; then
  "$PYTHON" "$PACKAGE_INSTALLER" "$@" </dev/tty || fail 'the bundled package installer did not complete.'
else
  "$PYTHON" "$PACKAGE_INSTALLER" "$@" || fail 'the bundled package installer did not complete.'
fi

info ''
info "Open a new terminal so the updated PATH applies, then run '$EXECUTABLE'."
info "Documentation: $SITE/apps/docs/?id=$APP_ID"
