#Requires -Version 5.1
<#
    One-line installer for zai-editor (zai-editor).

        irm https://phoenixzqy.github.io/install/zai-editor.ps1 | iex

    Generated by scripts/build-installers.mjs from
    install/templates/installer.ps1.in. Edit the template, not this file, and
    re-run `npm run build:installers`.

    Environment overrides:
      ZAI_INSTALL_DIR           Installation directory (default: %USERPROFILE%\.zai).
      ZAI_RELEASE_MANIFEST_URL  Release manifest URL (used by the test suite).
      ZAI_INSTALL_ARGS          Extra arguments, because `irm | iex` passes none.
#>

Set-StrictMode -Version 1.0
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$appId = 'zai-editor'
$executable = 'zai-editor.exe'
$displayName = 'zai-editor'
$site = 'https://phoenixzqy.github.io'

function Get-ZaiEnv([string] $name) {
    $value = [Environment]::GetEnvironmentVariable($name)
    if ([string]::IsNullOrWhiteSpace($value)) { return $null }
    return $value
}

function Stop-Install([string] $message, [int] $code = 1) {
    [Console]::Error.WriteLine("$displayName installer: $message")
    exit $code
}

$manifestUrl = Get-ZaiEnv 'ZAI_RELEASE_MANIFEST_URL'
if (-not $manifestUrl) { $manifestUrl = "$site/releases/$appId/latest/manifest.json" }
$installDir = Get-ZaiEnv 'ZAI_INSTALL_DIR'
if (-not $installDir) { $installDir = Join-Path $env:USERPROFILE '.zai' }

# Windows PowerShell 5.1 may still default to TLS 1.0; PowerShell 7 ignores this.
try {
    [Net.ServicePointManager]::SecurityProtocol =
        [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
} catch {
    Write-Verbose 'The TLS 1.2 protocol could not be selected explicitly.'
}

function Get-Architecture {
    try {
        switch ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()) {
            'X64' { return 'x64' }
            'Arm64' { return 'arm64' }
        }
    } catch {
        Write-Verbose 'RuntimeInformation is unavailable; falling back to the environment.'
    }
    $raw = $env:PROCESSOR_ARCHITEW6432
    if ([string]::IsNullOrWhiteSpace($raw)) { $raw = $env:PROCESSOR_ARCHITECTURE }
    switch ($raw) {
        'AMD64' { return 'x64' }
        'ARM64' { return 'arm64' }
    }
    Stop-Install "unsupported processor architecture: $raw. Published builds cover x64 and arm64."
}

function Save-Download([string] $url, [string] $destination) {
    if (-not $url.StartsWith('https://') -and -not (Get-ZaiEnv 'ZAI_RELEASE_MANIFEST_URL')) {
        Stop-Install "refusing to download over a non-HTTPS URL: $url"
    }
    try {
        Invoke-WebRequest -Uri $url -OutFile $destination -UseBasicParsing
    } catch {
        Stop-Install "download failed: $url ($($_.Exception.Message))"
    }
}

function Add-UserPath([string] $directory) {
    # The user PATH is read and written through the registry rather than
    # [Environment]::GetEnvironmentVariable/SetEnvironmentVariable: those expand
    # %VARIABLE% references on read and always write a plain string, which would
    # permanently freeze entries such as %USERPROFILE%\bin to today's value and
    # downgrade REG_EXPAND_SZ to REG_SZ.
    $key = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Environment', $true)
    if ($null -eq $key) {
        $key = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey('Environment')
    }
    try {
        $current = $key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
        $kind = if ($null -eq $key.GetValue('Path')) { [Microsoft.Win32.RegistryValueKind]::ExpandString } else { $key.GetValueKind('Path') }
        if ($null -eq $current) { $current = '' }
        $entries = @([string]$current -split ';' | Where-Object { $_ })
        $normalized = $directory.TrimEnd('\')
        foreach ($entry in $entries) {
            if ([Environment]::ExpandEnvironmentVariables($entry).TrimEnd('\') -ieq $normalized) {
                Write-Host "$directory is already on your user PATH."
                return
            }
        }
        $updated = (@($entries) + $directory) -join ';'
        $key.SetValue('Path', $updated, $kind)
        Write-Host "Added $directory to your user PATH."
    } finally {
        $key.Close()
    }
}

$architecture = Get-Architecture
$work = Join-Path ([System.IO.Path]::GetTempPath()) ("zai-install-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $work -Force | Out-Null

try {
    $manifestFile = Join-Path $work 'manifest.json'
    Save-Download $manifestUrl $manifestFile
    try {
        $manifest = Get-Content -Path $manifestFile -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
        Stop-Install "the release manifest at $manifestUrl could not be read as JSON."
    }

    if ($null -eq $manifest.release) {
        [Console]::Error.WriteLine("No public release of $displayName has been published yet.")
        [Console]::Error.WriteLine("Watch $site/apps/app/?id=$appId for the first build.")
        exit 2
    }

    $asset = $manifest.release.assets |
        Where-Object {
            $_.platform -eq 'windows' -and
            $_.architecture -eq $architecture -and
            ([string] $_.file) -match '\.zip$'
        } |
        Select-Object -First 1
    if ($null -eq $asset) {
        Stop-Install "the published release has no package for windows/$architecture. See $site/apps/releases/?id=$appId for the packages that are available."
    }
    if ($asset.file -match '[\\/]' -or $asset.file -match '\.\.') {
        Stop-Install "the manifest package name is not a plain filename: $($asset.file)"
    }

    $assetUrl = Get-Member -InputObject $asset -Name 'url' -MemberType NoteProperty |
        ForEach-Object { $asset.url }
    if ([string]::IsNullOrWhiteSpace($assetUrl)) {
        $assetUrl = ($manifestUrl -replace '/[^/]*$', '') + '/' + $asset.file
    }

    $archive = Join-Path $work $asset.file
    Write-Host "Downloading $displayName for windows/$architecture..."
    Save-Download $assetUrl $archive

    $actualHash = (Get-FileHash -Path $archive -Algorithm SHA256).Hash.ToLowerInvariant()
    $expectedHash = ([string] $asset.sha256).ToLowerInvariant()
    if ($actualHash -ne $expectedHash) {
        Stop-Install "SHA-256 verification failed for $($asset.file).`n  expected: $expectedHash`n  actual:   $actualHash`nThe download was discarded and nothing was installed."
    }
    $actualBytes = (Get-Item -Path $archive).Length
    $expectedBytes = Get-Member -InputObject $asset -Name 'bytes' -MemberType NoteProperty |
        ForEach-Object { $asset.bytes }
    if ($expectedBytes -and $actualBytes -ne $expectedBytes) {
        Stop-Install "the downloaded package is $actualBytes bytes but the manifest declares $expectedBytes. Nothing was installed."
    }
    Write-Host "Verified SHA-256 $expectedHash"

    $extract = Join-Path $work 'extract'
    New-Item -ItemType Directory -Path $extract -Force | Out-Null
    try {
        Expand-Archive -Path $archive -DestinationPath $extract -Force
    } catch {
        Stop-Install "the downloaded archive could not be extracted: $($_.Exception.Message)"
    }

    # --- Install ----------------------------------------------------------
    $binary = Get-ChildItem -Path $extract -Filter $executable -Recurse -File |
        Select-Object -First 1
    if ($null -eq $binary) {
        Stop-Install "the package did not contain an executable named '$executable'. Nothing was installed."
    }

    New-Item -ItemType Directory -Path $installDir -Force | Out-Null
    $target = Join-Path $installDir $executable
    Copy-Item -Path $binary.FullName -Destination $target -Force

    $licenseDir = Join-Path (Join-Path $installDir 'licenses') $appId
    if (Test-Path $licenseDir) { Remove-Item -Path $licenseDir -Recurse -Force }
    New-Item -ItemType Directory -Path $licenseDir -Force | Out-Null
    Get-ChildItem -Path $extract -Recurse -File |
        Where-Object { $_.Name -match '^(LICENSE|NOTICE|COPYING|THIRD[-_]PARTY)' } |
        ForEach-Object { Copy-Item -Path $_.FullName -Destination $licenseDir -Force }

    Add-UserPath $installDir

    Write-Host ''
    Write-Host "Installed $displayName to $target"
    Write-Host "Licenses: $licenseDir"
    Write-Host "Open a new terminal so the updated PATH applies, then run 'zai-editor'."
    Write-Host "Documentation: $site/apps/docs/?id=$appId"
} finally {
    Remove-Item -Path $work -Recurse -Force -ErrorAction SilentlyContinue
}
