#!/bin/sh
# One-line installer for zai-editor (zai-editor).
#
#   curl -fsSL https://phoenixzqy.github.io/install/zai-editor.sh | sh
#
# Generated by scripts/build-installers.mjs from
# install/templates/installer.sh.in. Edit the template, not this file, and
# re-run `npm run build:installers`.
#
# Environment overrides:
#   ZAI_INSTALL_DIR            Installation directory (default: $HOME/.zai).
#   ZAI_RELEASE_MANIFEST_URL   Release manifest URL (used by the test suite).
set -eu

APP_ID='zai-editor'
EXECUTABLE='zai-editor'
DISPLAY_NAME='zai-editor'
SITE='https://phoenixzqy.github.io'
MANIFEST_URL="${ZAI_RELEASE_MANIFEST_URL:-$SITE/releases/$APP_ID/latest/manifest.json}"
INSTALL_DIR="${ZAI_INSTALL_DIR:-$HOME/.zai}"

WORK=''
cleanup() {
  if [ -n "$WORK" ]; then
    rm -rf "$WORK"
  fi
}
trap cleanup EXIT HUP INT TERM

fail() {
  printf '%s installer: %s\n' "$DISPLAY_NAME" "$1" >&2
  exit 1
}
info() {
  printf '%s\n' "$1"
}

# Detect the calling shell, not /bin/sh used to run this installer. SHELL is
# the login-shell fallback when the parent is a wrapper or cannot be inspected.
activation_shell=${SHELL:-}
activation_shell=${activation_shell##*/}
if command -v ps >/dev/null 2>&1; then
  parent_shell=$(ps -p "$PPID" -o comm= 2>/dev/null | sed 's/^[[:space:]]*//; s/^-//')
  parent_shell=${parent_shell##*/}
  case "$parent_shell" in
    bash | zsh | sh | dash | ksh | fish) activation_shell=$parent_shell ;;
  esac
fi

quote_shell() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

quote_fish() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g")"
}

show_activation() {
  activation_dir=$1
  activation_executable=$2
  activation_profile=''
  case "$activation_shell" in
    zsh) activation_profile="$HOME/.zshrc" ;;
    bash) activation_profile="$HOME/.bashrc" ;;
    sh | dash | ksh) activation_profile="$HOME/.profile" ;;
  esac
  printf '\n%s\n' 'To use the app in this terminal, copy and run:'
  quoted_activation_dir=$(quote_shell "$activation_dir")
  case "$activation_shell" in
    bash | zsh | sh | dash | ksh)
      # A profile text match is only a hint; always activate the actual directory.
      if [ -n "$activation_profile" ] && [ -f "$activation_profile" ] &&
          { grep -Fq -- "$activation_dir" "$activation_profile" ||
            grep -Fq -- "$quoted_activation_dir" "$activation_profile"; }; then
        case "$activation_shell" in bash | zsh) source_command=source ;; *) source_command=. ;; esac
        printf '  %s %s\n' "$source_command" "$(quote_shell "$activation_profile")"
      fi
      printf '  export PATH=%s:"$PATH"\n' "$quoted_activation_dir"
      printf '  %s\n' "$(quote_shell "$activation_executable")"
      ;;
    fish)
      printf '  set -gx PATH %s $PATH\n' "$(quote_fish "$activation_dir")"
      printf '  %s\n' "$(quote_fish "$activation_executable")"
      ;;
    *)
      printf '%s\n' 'Shell not recognized. Add the installation directory to PATH using your shell settings, or launch directly:'
      printf '  %s\n' "$(quote_shell "$activation_dir/$activation_executable")"
      ;;
  esac
  printf '%s\n' 'Run the command above in your current shell; a child installer cannot update its parent shell.'
}
# --- Platform -------------------------------------------------------------
case "$(uname -s)" in
  Linux*) PLATFORM=linux ;;
  Darwin*) PLATFORM=macos ;;
  *) fail "unsupported operating system: $(uname -s). Published builds cover Linux (including WSL) and macOS here; on Windows run the PowerShell installer at $SITE/install/$APP_ID.ps1." ;;
esac
case "$(uname -m)" in
  x86_64 | amd64) ARCHITECTURE=x64 ;;
  aarch64 | arm64) ARCHITECTURE=arm64 ;;
  *) fail "unsupported processor architecture: $(uname -m). Published builds cover x86_64/amd64 and aarch64/arm64." ;;
esac

# --- Tools ----------------------------------------------------------------
PYTHON=''
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 &&
      "$candidate" -c 'import sys; sys.exit(sys.version_info < (3, 0))' >/dev/null 2>&1; then
    PYTHON="$candidate"
    break
  fi
done
[ -n "$PYTHON" ] ||
  fail 'A working Python 3 or newer is required on PATH (python3 or python). Install it from https://www.python.org/downloads/, open a new terminal, and rerun the installer. Nothing was installed.'

if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
  fail 'no SHA-256 tool was found. Install sha256sum (coreutils) or shasum and run the command again. Nothing was installed.'
fi
if command -v curl >/dev/null 2>&1; then
  DOWNLOADER=curl
elif command -v wget >/dev/null 2>&1; then
  DOWNLOADER=wget
else
  fail 'neither curl nor wget was found. Install one of them and run the command again.'
fi

require_https() {
  case "$1" in
    https://*) return 0 ;;
  esac
  if [ -n "${ZAI_RELEASE_MANIFEST_URL:-}" ]; then
    case "$1" in
      http://127.0.0.1 | http://127.0.0.1/* | http://127.0.0.1:*)
        authority=${1#http://}
        authority=${authority%%/*}
        case "$authority" in
          127.0.0.1) return 0 ;;
          127.0.0.1:*)
            port=${authority#127.0.0.1:}
            case "$port" in '' | *[!0-9]*) ;; *) return 0 ;; esac
            ;;
        esac
        ;;
    esac
  fi
  fail "refusing to download over a non-HTTPS URL: $1"
}

download() {
  require_https "$1"
  case "$DOWNLOADER" in
    curl)
      case "$1" in
        https://*) curl -fsSL --proto '=https' --proto-redir '=https' -o "$2" "$1" ;;
        *) curl -fsSL --proto '=http' --max-redirs 0 -o "$2" "$1" ;;
      esac || fail "download failed: $1"
      ;;
    wget)
      case "$1" in
        https://*) wget -q --https-only -O "$2" "$1" ;;
        *) wget -q --max-redirect=0 -O "$2" "$1" ;;
      esac || fail "download failed: $1"
      ;;
  esac
}

checksum() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    fail 'no SHA-256 tool was found. Install sha256sum (coreutils) or shasum and run the command again.'
  fi
}

extract() {
  if command -v unzip >/dev/null 2>&1; then
    unzip -q "$1" -d "$2" || fail 'the downloaded archive could not be extracted with unzip.'
  elif command -v bsdtar >/dev/null 2>&1; then
    bsdtar -xf "$1" -C "$2" || fail 'the downloaded archive could not be extracted with bsdtar.'
  elif tar -xf "$1" -C "$2" 2>/dev/null; then
    :
  else
    "$PYTHON" -m zipfile -e "$1" "$2" || fail 'the downloaded archive could not be extracted with Python.'
  fi
}

ensure_on_path() {
  marker='# Added by zai installer'
  quoted_dir="$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
  line="export PATH='$quoted_dir':\"\$PATH\"  $marker"
  profiles="$HOME/.profile"
  case "$activation_shell" in
    zsh) profiles="$profiles $HOME/.zshrc" ;;
    bash) profiles="$profiles $HOME/.bashrc" ;;
    *) profiles="$profiles $HOME/.bashrc $HOME/.zshrc" ;;
  esac
  for profile in $profiles; do
    # Match the exact line, not the marker: an earlier install into a
    # different directory must not make this one think PATH is already set.
    if [ -f "$profile" ] && grep -Fqx "$line" "$profile"; then
      continue
    fi
    if [ -f "$profile" ] && [ -n "$(tail -c 1 "$profile" 2>/dev/null)" ]; then
      printf '\n' >>"$profile" || continue
    fi
    printf '%s\n' "$line" >>"$profile" 2>/dev/null || continue
    info "Added $1 to PATH in $profile"
  done
}

# --- Manifest -------------------------------------------------------------
WORK="$(mktemp -d 2>/dev/null || mktemp -d -t zai-install)" ||
  fail 'a temporary directory could not be created.'
MANIFEST="$WORK/manifest.json"
download "$MANIFEST_URL" "$MANIFEST"

if ASSET="$("$PYTHON" - "$MANIFEST" "$PLATFORM" "$ARCHITECTURE" <<'PY'
import json
import sys

try:
    with open(sys.argv[1], encoding="utf-8") as manifest_file:
        manifest = json.load(manifest_file)
    if manifest["release"] is None:
        raise SystemExit(2)
    assets = manifest["release"]["assets"]
    if not isinstance(assets, list):
        raise TypeError
    asset = next(
        (
            candidate
            for candidate in assets
            if isinstance(candidate, dict)
            and candidate.get("platform") == sys.argv[2]
            and candidate.get("architecture") == sys.argv[3]
        ),
        None,
    )
    if asset is not None:
        file = asset["file"]
        url = asset.get("url", "")
        sha256 = asset["sha256"]
        byte_count = asset.get("bytes", "")
        if not all(isinstance(value, str) for value in (file, url, sha256)):
            raise TypeError
        if byte_count != "" and (not isinstance(byte_count, int) or isinstance(byte_count, bool)):
            raise TypeError
        print(file, url, sha256, byte_count, sep="\n")
except (KeyError, OSError, TypeError, json.JSONDecodeError):
    raise SystemExit(1)
PY
)"; then
  :
else
  status=$?
  if [ "$status" -eq 2 ]; then
    printf '%s\n' "No public release of $DISPLAY_NAME has been published yet." >&2
    printf '%s\n' "Watch $SITE/apps/app/?id=$APP_ID for the first build." >&2
    exit 2
  fi
  fail "the release manifest at $MANIFEST_URL could not be read as valid JSON."
fi

[ -n "$ASSET" ] ||
  fail "the published release has no package for $PLATFORM/$ARCHITECTURE. See $SITE/apps/releases/?id=$APP_ID for the packages that are available."

ASSET_FILE="$(printf '%s\n' "$ASSET" | sed -n 1p)"
ASSET_URL="$(printf '%s\n' "$ASSET" | sed -n 2p)"
ASSET_SHA="$(printf '%s\n' "$ASSET" | sed -n 3p)"
ASSET_BYTES="$(printf '%s\n' "$ASSET" | sed -n 4p)"

case "$ASSET_FILE" in
  */* | *..* | '') fail "the manifest package name is not a plain filename: $ASSET_FILE" ;;
esac
if [ -z "$ASSET_URL" ]; then
  ASSET_URL="${MANIFEST_URL%/*}/$ASSET_FILE"
fi

# --- Download and verify --------------------------------------------------
ARCHIVE="$WORK/$ASSET_FILE"
info "Downloading $DISPLAY_NAME for $PLATFORM/$ARCHITECTURE…"
download "$ASSET_URL" "$ARCHIVE"

ACTUAL_SHA="$(checksum "$ARCHIVE")"
if [ "$ACTUAL_SHA" != "$ASSET_SHA" ]; then
  fail "SHA-256 verification failed for $ASSET_FILE.
  expected: $ASSET_SHA
  actual:   $ACTUAL_SHA
The download was discarded and nothing was installed."
fi
if [ -n "$ASSET_BYTES" ]; then
  ACTUAL_BYTES="$(wc -c <"$ARCHIVE" | tr -d ' ')"
  if [ "$ACTUAL_BYTES" != "$ASSET_BYTES" ]; then
    fail "the downloaded package is $ACTUAL_BYTES bytes but the manifest declares $ASSET_BYTES. Nothing was installed."
  fi
fi
info "Verified SHA-256 $ASSET_SHA"

EXTRACT="$WORK/extract"
mkdir -p "$EXTRACT"
extract "$ARCHIVE" "$EXTRACT"

# --- Install --------------------------------------------------------------
BIN="$(find "$EXTRACT" -type f -name "$EXECUTABLE" -print 2>/dev/null | sed -n 1p)"
[ -n "$BIN" ] ||
  fail "the package did not contain an executable named '$EXECUTABLE'. Nothing was installed."

mkdir -p "$INSTALL_DIR" || fail "the installation directory could not be created: $INSTALL_DIR"
STAGED="$INSTALL_DIR/.$EXECUTABLE.$$"
cp "$BIN" "$STAGED" || fail "the executable could not be written to $INSTALL_DIR."
chmod 0755 "$STAGED"
# Replace by rename so a running copy is never written in place.
mv -f "$STAGED" "$INSTALL_DIR/$EXECUTABLE" ||
  fail "the executable could not be installed into $INSTALL_DIR."

LICENSE_DIR="$INSTALL_DIR/licenses/$APP_ID"
rm -rf "$LICENSE_DIR"
mkdir -p "$LICENSE_DIR"
find "$EXTRACT" -type f \( -name 'LICENSE*' -o -name 'NOTICE*' -o -name 'COPYING*' \
  -o -name 'THIRD-PARTY*' -o -name 'THIRD_PARTY*' \) -exec cp {} "$LICENSE_DIR/" \; 2>/dev/null || true

ensure_on_path "$INSTALL_DIR"

info ''
info "Installed $DISPLAY_NAME to $INSTALL_DIR/$EXECUTABLE"
info "Licenses: $LICENSE_DIR"
show_activation "$INSTALL_DIR" "$EXECUTABLE"
info "Documentation: $SITE/apps/docs/?id=$APP_ID"
