import { readFile, readdir, lstat, realpath } from "node:fs/promises";
import { createReadStream } from "node:fs";
import { createHash } from "node:crypto";
import { resolve, join, dirname, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { validateCatalog, validateManifest, validateDocsIndex } from "../apps/schema.js";

const siteRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Every media file a catalog entry names has to exist in this repository as a
// regular file, so a detail page can never render a broken poster or video.
async function regularFile(root, href, label) {
  const file = join(root, href.replace(/^\//, ""));
  const stat = await lstat(file).catch(() => null);
  if (!stat || !stat.isFile() || stat.isSymbolicLink()) throw new Error(`${label}: ${href} must exist as a regular file.`);
  return stat.size;
}

async function validateMedia(root, catalog) {
  let bytes = 0;
  for (const app of catalog.apps) {
    if (app.artwork) bytes += await regularFile(root, app.artwork.src, app.id);
    for (const screenshot of app.screenshots ?? []) bytes += await regularFile(root, screenshot.src, app.id);
    for (const video of app.videos ?? []) {
      bytes += await regularFile(root, video.src, app.id);
      bytes += await regularFile(root, video.poster, app.id);
    }
  }
  return bytes;
}

// The documentation mirror is generated by scripts/sync-app-docs.mjs. The
// validator checks that what is committed matches its own index exactly, so a
// half-finished sync cannot ship a dangling or an unreviewed document.
async function validateDocs(root, catalog) {
  const sources = JSON.parse(await readFile(join(root, "apps/docs/sources.json"), "utf8"));
  let count = 0;
  for (const app of catalog.apps) {
    const folder = join(root, "apps/docs", app.id);
    const source = sources.apps.find((entry) => entry.appId === app.id);
    if (!app.documentation) {
      if (source) throw new Error(`${app.id}: apps/docs/sources.json lists documentation, but the catalog entry does not enable it.`);
      continue;
    }
    if (!source) throw new Error(`${app.id}: documentation is enabled but apps/docs/sources.json has no entry for it.`);
    const index = validateDocsIndex(JSON.parse(await readFile(join(folder, "index.json"), "utf8")), app);
    if (index.commit !== source.commit) throw new Error(`${app.id}: apps/docs/sources.json records ${source.commit}, but the mirror was built from ${index.commit}. Re-run scripts/sync-app-docs.mjs.`);
    if (await realpath(folder) !== resolve(folder)) throw new Error(`${app.id}: documentation folder must not contain symlinks.`);
    const expected = new Set(["index.json", ...index.documents.map((document_) => document_.file), ...index.assets]);
    const present = new Set();
    for (const entry of await readdir(folder, { withFileTypes: true, recursive: true })) {
      if (!entry.isFile()) continue;
      const relative = join(entry.parentPath ?? entry.path, entry.name).slice(folder.length + 1).split(sep).join("/");
      present.add(relative);
    }
    const missing = [...expected].filter((name) => !present.has(name));
    if (missing.length) throw new Error(`${app.id}: documentation files are missing: ${missing.join(", ")}. Re-run scripts/sync-app-docs.mjs.`);
    const unexpected = [...present].filter((name) => !expected.has(name));
    if (unexpected.length) throw new Error(`${app.id}: unlisted files in apps/docs/${app.id}/: ${unexpected.join(", ")}. Re-run scripts/sync-app-docs.mjs to remove stale documents.`);
    count += index.documents.length;
  }
  return count;
}

export async function validateSite(root = siteRoot) {
  const catalog = validateCatalog(JSON.parse(await readFile(join(root, "apps/catalog.json"), "utf8")));
  let totalBytes = 0;
  for (const app of catalog.apps) {
    const folder = join(root, "releases", app.id, "latest");
    const manifestPath = join(folder, "manifest.json");
    if ((await lstat(manifestPath)).isSymbolicLink()) throw new Error(`${app.id}: manifest must not be a symlink.`);
    const manifest = validateManifest(JSON.parse(await readFile(manifestPath, "utf8")), app);
    const expected = new Set(["manifest.json"]);
    if (await realpath(folder) !== resolve(folder)) throw new Error(`${app.id}: release folder must not contain symlinks.`);
    for (const asset of manifest.release?.assets ?? []) {
      if (asset.url) continue;
      expected.add(asset.file);
      const file = join(folder, asset.file);
      const stat = await lstat(file);
      if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`${app.id}/${asset.file}: package must be a regular file, not a symlink.`);
      if (stat.size !== asset.bytes) throw new Error(`${app.id}/${asset.file}: byte count does not match the manifest.`);
      const hash = createHash("sha256");
      for await (const chunk of createReadStream(file)) hash.update(chunk);
      if (hash.digest("hex") !== asset.sha256) throw new Error(`${app.id}/${asset.file}: SHA-256 does not match the manifest.`);
      totalBytes += stat.size;
    }
    const unexpected = (await readdir(folder)).filter((name) => !expected.has(name));
    if (unexpected.length) throw new Error(`${app.id}: unlisted files in latest/: ${unexpected.join(", ")}. Publish only approved packages and the manifest.`);
  }
  const mediaBytes = await validateMedia(root, catalog);
  const documents = await validateDocs(root, catalog);
  if (totalBytes >= 1024 ** 3) throw new Error("Local packages reach the 1 GiB Pages limit. Move packages to public GitHub Releases and leave room for the website.");
  return { apps: catalog.apps.length, localBytes: totalBytes, mediaBytes, documents };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const result = await validateSite();
    console.log(`Validated ${result.apps} app(s), release metadata, ${result.documents} mirrored document(s), ${result.mediaBytes} media bytes, and ${result.localBytes} local package bytes.`);
  } catch (error) {
    console.error(`App release validation failed: ${error.message}`);
    process.exitCode = 1;
  }
}
